<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <RootNamespace>BsCOpenSearchSync.Client</RootNamespace>

        <!-- NuGet package metadata -->
        <PackageId>BsCOpenSearchSync.Client</PackageId>
        <Version>1.2.24</Version>
        <Authors>PeterH2N</Authors>
        <Company>SDU</Company>
        <Description>Sync service</Description>
        <PackageTags>domain;ddd;shared</PackageTags>

        <!-- Generate package on build -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!-- Github packages -->
        <PackageProjectUrl>https://github.com/PeterH2N/REPO</PackageProjectUrl>
        <RepositoryUrl>https://github.com/PeterH2N/Bachelor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BsCOpenSearchSync.DataAccess\BsCOpenSearchSync.DataAccess.csproj" />
      <ProjectReference Include="..\BsCOpenSearchSync.Domain\BsCOpenSearchSync.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="bsccaseapi.domain" Version="1.2.24" />
    </ItemGroup>

</Project>
