<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>BsCOpenSearchSync.Business</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BsCCaseApi.DataAccess" Version="1.2.29" />
      <PackageReference Include="BsCCaseapi.Domain" Version="1.2.29" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BsCOpenSearchSync.DataAccess\BsCOpenSearchSync.DataAccess.csproj" />
      <ProjectReference Include="..\BsCOpenSearchSync.Domain\BsCOpenSearchSync.Domain.csproj" />
    </ItemGroup>

</Project>
