<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BsCCaseApi.Domain</RootNamespace>
        <IsPackable>true</IsPackable>

        <!-- NuGet package metadata -->
        <PackageId>BsCCaseApi.Domain</PackageId>
        <Version>1.2.33</Version>
        <Authors>PeterH2N</Authors>
        <Company>SDU</Company>
        <Description>Domain models and value objects for BsCCaseApi.</Description>
        <PackageTags>domain;ddd;shared</PackageTags>

        <!-- Generate package on build -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!-- Github packages -->
        <PackageProjectUrl>https://github.com/PeterH2N/REPO</PackageProjectUrl>
        <RepositoryUrl>https://github.com/PeterH2N/Bachelor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
    </PropertyGroup>

</Project>
