<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>

        <!-- NuGet package metadata -->
        <PackageId>BsCCaseApi.Domain</PackageId>
        <Version>1.0.3</Version>
        <Authors>PeterH2N</Authors>
        <Company>SDU</Company>
        <Description>Domain models and value objects for BsCCaseApi.</Description>
        <PackageTags>domain;ddd;shared</PackageTags>

        <!-- Generate package on build -->
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>BsCCaseApi.Domain</RootNamespace>
    </PropertyGroup>

</Project>
