<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>BsCCaseApi</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="bscopensearchsync.client" Version="1.2.32" />
        <PackageReference Include="DotNetEnv" Version="3.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BsCCaseApi.Business\BsCCaseApi.Business.csproj" />
      <ProjectReference Include="..\BsCCaseApi.Domain\BsCCaseApi.Domain.csproj" />
      <ProjectReference Include="..\BsCCaseApi.DataAccess\BsCCaseApi.DataAccess.csproj" />
    </ItemGroup>

</Project>
