<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <RootNamespace>BsCOpenSearchSync.Domain</RootNamespace>

        <!-- NuGet package metadata -->
        <PackageId>BsCOpenSearchSync.Domain</PackageId>
        <Version>1.2.35</Version>
        <Authors>PeterH2N</Authors>
        <Company>SDU</Company>
        <Description>Domain models and value objects for BsCCaseApi.</Description>
        <PackageTags>domain;ddd;shared</PackageTags>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        
        <!-- Github packages -->
        <PackageProjectUrl>https://github.com/PeterH2N/REPO</PackageProjectUrl>
        <RepositoryUrl>https://github.com/PeterH2N/Bachelor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        
    </PropertyGroup>

</Project>
